theme: jekyll-theme-minimal
title: Sem-UNComa
description: La Sociología y el giro digital - Herramientas computacionales para el análisis de la conflictividad en la era del Big Data
logo: https://raw.githubusercontent.com/agusnieto77/Sem-UNComa/master/seminario.png
favicon: img/favicon.ico
show_downloads: false
