theme: jekyll-theme-minimal
title: Sem-HCACSo
description: Seminario de posgrado 'Herramientas computacionales para el análisis de la conflictividad social'
logo: https://estudiosmaritimossociales.org/seminario03.png
favicon: img/favicon.ico
show_downloads: false
