---
output: md_document
---

# Bibliografía

## Unidad I

### Obligatoria

-   Aragona, B. (2022). Tipos de big data y análisis sociológico: usos, críticas y problemas éticos. Empiria. Revista De metodología De Ciencias Sociales, (53), 15–30  ([link](https://revistas.uned.es/index.php/empiria/article/view/32610/24783 "Tipos de big data y análisis sociológico")).

-   Cabrera-Álvarez, P. (2022). Survey Research in Times of Big Data. Empiria. Revista De metodología De Ciencias Sociales, (53), 31–51 ([link](https://github.com/agusnieto77/Sem-HCACSo/raw/main/docs/biblio/Pons%20-%20D%C3%B3nde%20est%C3%A1%20el%20archivo%20V.pdf "Survey Research in Times of Big Data")).

-   Gualda, Estrella (2022) Social big data, sociología y ciencias sociales computacionales. *Empiria: Revista de metodología de ciencias sociales*, 53, 147-177  ([link](https://revistas.uned.es/index.php/empiria/article/view/32631/24825 "Social big data, sociología y ciencias sociales computacionales")).

-   Piovani, Juan Ignacio, y Paolo Parra Saiani. «Triangulación metodológica y big data». PRACS: Revista Eletrônica de Humanidades do Curso de Ciências Sociais da UNIFAP 14, nº 2 (26 de febrero de 2022): 157-67  ([link](https://sci-hub.se/https://doi.org/10.1080/01576895.2019.1640753 "Triangulación metodológica y big data")).


## Unidad II

### Obligatoria

-   Albrieu, Ramiro & Palazzo, Gabriel (2020) Categorización de conflictos sociales en el ámbito de los recursos naturales: Un estudio de las actividades extractivas mediante la minería de textos. Revista CEPAL, 131, 29--59 ([link](https://repositorio.cepal.org/bitstream/handle/11362/45952/RVE131_Albrieu.pdf?sequence=1&isAllowed=y "Categorización de conflictos sociales en el ámbito de los recursos naturales")).

-   Franzosi, Roberto (2020) What's in a text? Bridging the gap between quality and quantity in the digital era. Quality & Quantity, 1-28 ([link](https://sci-hub.se/https://doi.org/10.1007/s11135-020-01067-6 "What's in a text?")).

-   Nieto, Agustín, Silvana Ferreyra y Emiliano Calomarde (2022) La pandemia en el pago chico. Agenda mediática y comentarios de lectorxs en Mar del Plata, 2020-2021. Ferrari, Marcela *Memorias del COVID. Partido de General Pueyrredon, 2020 - 2021*, Rosario: Prohistoria ([link](https://www.academia.edu/77606214/TIEMPOS_DE_PANDEMIA "La pandemia en el pago chico")).

### Complementaria

-   Liang, H., & Zhu, J. J. (2017). Big data, collection of (social media, harvesting). The International Encyclopedia of Communication Research Methods, 1--18 ([link](https://sci-hub.se/https://doi.org/10.1002/9781118901731.iecrm0015 "Big data, collection of (social media, harvesting)")). 

-   Palazzo, Gabriel (2017). Minerı́a de datos, conflictos sociales y explotación de recursos naturales: un aporte metodológico. Compendium: Cuadernos de Economı́a y Administración, 4(7) ([link](http://www.revistas.espol.edu.ec/index.php/compendium/article/view/179/165 "Minerı́a de datos, conflictos sociales y explotación de recursos naturales")).

## Unidad III

### Obligatoria

-   Bradley, Alex, y Richard James (2019) Web Scraping Using R. *Advances in Methods and Practices in Psychological Science*, 2, 3, 264-70 ([link](https://doi.org/10.1177/2515245919859535 "Web Scraping Using R")).

-   Laitano, Guillermina y Nieto, Agustín (2021) Activismo barrial en perspectiva histórica: un acercamiento computacional, Informe técnico, PI3CET, ([link](https://gesmar.estudiosmaritimossociales.org/Informe_GESMar_PI3CET_parte1.html "Activismo barrial en perspectiva histórica")).

-   Müller, Kirill & Wickham, Hadley (2022) Tibble: Simple data frames ([link](https://cran.r-project.org/web/packages/tibble/tibble.pdf "Tibble")).

### Complementaria

-   Ulbricht, Lena (2020) Scraping the demos. Digitalization, web scraping and the democratic project. *Democratization*, 27, 3, 426-42 ([link](https://doi.org/10.1080/13510347.2020.1714595 "Scraping the demos")).

-   Wickham, Hadley (2021) *Rvest: easily harvest (scrape) web pages* ([link](https://cran.r-project.org/web/packages/rvest/rvest.pdf "easily harvest (scrape) web pages")).

-   Wickham, Hadley & Cia. (2019) Welcome to the tidyverse. *Journal of Open Source Software*, 4(43), 1686 ([link](https://doi.org/10.21105/joss.01686 "Welcome to the tidyverse")).

## Unidad IV

### Obligatoria

-   Laitano, Guillermina y Nieto, Agustín (2022) La conflictividad social en los barrios de Mar del Plata (2016-2020): un acercamiento computacional. Laitano y Nieto *La conflictividad social en la historia reciente: estudios sociohistóricos entre lo local y lo regional*, Buenos Aires, TeseoPress ([link](https://github.com/agusnieto77/Sem-HCACSo/raw/main/bibliograf%C3%ADa/La-conflictividad-social-en-la-historia-reciente_cap-3.pdf "La conflictividad social en los barrios")).

-   Melo, Jairo (2017) Lectura distante, fragmentada y colaborativa en el archivo infinito. *Relaciones: Estudios de historia y sociedad*, 38,149, 169-89 ([link](https://www.scielo.org.mx/pdf/rz/v38n149/2448-7554-rz-38-149-00169.pdf "Lectura distante, fragmentada y colaborativa en el archivo infinito")).

-   Moretti, Franco (2015) El matadero de la literatura. *Lectura distant*e, FCE, Buenos Aires ([link](https://github.com/agusnieto77/Sem-HCACSo/raw/main/docs/biblio/Moretti%20-%20El%20matadero%20de%20la%20literatura%20III.pdf "El matadero de la literatura")).

### Complementaria

-   Mueller, Martin (2012) Scalable Reading. *Scalablereading* ([link](https://scalablereading.northwestern.edu/?page_id=22 "Scalable Reading")).

-   Silge, Julia & Robinson, David (2017) *Text mining with r: a tidy approach*. O'Reilly Media, Inc. ([link](https://www.tidytextmining.com/ "Text mining with r")).

## Unidad V

### Obligatoria

-   Cairo, Alberto (2017) Visualización de datos: una imagen puede valer más que mil números, pero no siempre más que mil palabras. *Profesional de la información*, 26, 6, 1025-28 ([link](https://doi.org/10.3145/epi.2017.nov.02 "Visualización de datos")).

-   Nieto, Agustín (2021) Intersecciones entre historia digital e historia social: un ejercicio de lectura distante sobre la conflictividad marítima en la historia argentina reciente. *Drassana*, 28, 122--142 ([link](https://doi.org/10.51829/Drassana.28.650 "Intersecciones entre historia digital e historia social")).

-   Rosati, German (2020) La visualización de datos es trabajo esencial. Factor\~data (blog), *Medium* ([link](https://medium.com/factor-data/la-visualizaci%C3%B3n-de-datos-es-trabajo-esencial-ea7acc20b5d3 "La visualización de datos es trabajo esencial"))

### Complementaria

-   Schwandt, Silke (2019) Métodos digitales para la semántica histórica. Tras el rastro de los conceptos en corpus digitales. *Conceptos históricos*, 8, 5, 160-196 ([link](https://revistasacademicas.unsam.edu.ar/index.php/conhist/article/download/79/63/125 "Métodos digitales para la semántica histórica")).

-   Wickham, Hadley (2016) *ggplot2: Elegant graphics for data analysis*. Springer-Verlag New York ([link](https://github.com/agusnieto77/Sem-HCACSo/raw/main/docs/biblio/Hadley%20Wickham%20-%20ggplot2_%20Elegant%20Graphics%20for%20Data%20Analysis.pdf "ggplot2")).
